<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <InvariantGlobalization>false</InvariantGlobalization>
    <AssemblyName>Smbn.Engine</AssemblyName>
    <RootNamespace>Smbn.Engine</RootNamespace>
    <Version>0.1.0</Version>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SMBLibrary" Version="1.5.7" />
    <PackageReference Include="SMBLibrary.Win32" Version="1.5.7" />
  </ItemGroup>
</Project>
